// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waste.proto

package waste

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State_RUNNING  State = 0
	State_PENDING  State = 1
	State_SUCCESS  State = 2
	State_FAILURE  State = 3
	State_APPROVAL State = 4
)

var State_name = map[int32]string{
	0: "RUNNING",
	1: "PENDING",
	2: "SUCCESS",
	3: "FAILURE",
	4: "APPROVAL",
}
var State_value = map[string]int32{
	"RUNNING":  0,
	"PENDING":  1,
	"SUCCESS":  2,
	"FAILURE":  3,
	"APPROVAL": 4,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_waste_f5462c0924fc6b78, []int{0}
}

type Filter struct {
	Uuid                 []string `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	Artifact             []string `protobuf:"bytes,2,rep,name=artifact,proto3" json:"artifact,omitempty"`
	Cluster              []string `protobuf:"bytes,3,rep,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_waste_f5462c0924fc6b78, []int{0}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetUuid() []string {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Filter) GetArtifact() []string {
	if m != nil {
		return m.Artifact
	}
	return nil
}

func (m *Filter) GetCluster() []string {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type Host struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_waste_f5462c0924fc6b78, []int{1}
}
func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (dst *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(dst, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Host) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GHosts struct {
	Leader               *Host    `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Source               *Host    `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Lagger               *Host    `protobuf:"bytes,3,opt,name=lagger,proto3" json:"lagger,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GHosts) Reset()         { *m = GHosts{} }
func (m *GHosts) String() string { return proto.CompactTextString(m) }
func (*GHosts) ProtoMessage()    {}
func (*GHosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_waste_f5462c0924fc6b78, []int{2}
}
func (m *GHosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GHosts.Unmarshal(m, b)
}
func (m *GHosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GHosts.Marshal(b, m, deterministic)
}
func (dst *GHosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GHosts.Merge(dst, src)
}
func (m *GHosts) XXX_Size() int {
	return xxx_messageInfo_GHosts.Size(m)
}
func (m *GHosts) XXX_DiscardUnknown() {
	xxx_messageInfo_GHosts.DiscardUnknown(m)
}

var xxx_messageInfo_GHosts proto.InternalMessageInfo

func (m *GHosts) GetLeader() *Host {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *GHosts) GetSource() *Host {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *GHosts) GetLagger() *Host {
	if m != nil {
		return m.Lagger
	}
	return nil
}

type Change struct {
	Artifact             string    `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Cluster              string    `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Db                   string    `protobuf:"bytes,3,opt,name=db,proto3" json:"db,omitempty"`
	Table                string    `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Ddl                  string    `protobuf:"bytes,5,opt,name=ddl,proto3" json:"ddl,omitempty"`
	Leaders              []*Host   `protobuf:"bytes,6,rep,name=leaders,proto3" json:"leaders,omitempty"`
	Groups               []*GHosts `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_waste_f5462c0924fc6b78, []int{3}
}
func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (dst *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(dst, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetArtifact() string {
	if m != nil {
		return m.Artifact
	}
	return ""
}

func (m *Change) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Change) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *Change) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Change) GetDdl() string {
	if m != nil {
		return m.Ddl
	}
	return ""
}

func (m *Change) GetLeaders() []*Host {
	if m != nil {
		return m.Leaders
	}
	return nil
}

func (m *Change) GetGroups() []*GHosts {
	if m != nil {
		return m.Groups
	}
	return nil
}

type ChangeStatus struct {
	ChangeState          State                `protobuf:"varint,1,opt,name=change_state,json=changeState,proto3,enum=waste.State" json:"change_state,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Uuid                 string               `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ScheduledAt          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Progress             int32                `protobuf:"varint,7,opt,name=progress,proto3" json:"progress,omitempty"`
	Eta                  *duration.Duration   `protobuf:"bytes,8,opt,name=eta,proto3" json:"eta,omitempty"`
	Change               *Change              `protobuf:"bytes,9,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChangeStatus) Reset()         { *m = ChangeStatus{} }
func (m *ChangeStatus) String() string { return proto.CompactTextString(m) }
func (*ChangeStatus) ProtoMessage()    {}
func (*ChangeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_waste_f5462c0924fc6b78, []int{4}
}
func (m *ChangeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatus.Unmarshal(m, b)
}
func (m *ChangeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatus.Marshal(b, m, deterministic)
}
func (dst *ChangeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatus.Merge(dst, src)
}
func (m *ChangeStatus) XXX_Size() int {
	return xxx_messageInfo_ChangeStatus.Size(m)
}
func (m *ChangeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatus proto.InternalMessageInfo

func (m *ChangeStatus) GetChangeState() State {
	if m != nil {
		return m.ChangeState
	}
	return State_RUNNING
}

func (m *ChangeStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChangeStatus) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ChangeStatus) GetScheduledAt() *timestamp.Timestamp {
	if m != nil {
		return m.ScheduledAt
	}
	return nil
}

func (m *ChangeStatus) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ChangeStatus) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *ChangeStatus) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *ChangeStatus) GetEta() *duration.Duration {
	if m != nil {
		return m.Eta
	}
	return nil
}

func (m *ChangeStatus) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

func init() {
	proto.RegisterType((*Filter)(nil), "waste.Filter")
	proto.RegisterType((*Host)(nil), "waste.Host")
	proto.RegisterType((*GHosts)(nil), "waste.GHosts")
	proto.RegisterType((*Change)(nil), "waste.Change")
	proto.RegisterType((*ChangeStatus)(nil), "waste.ChangeStatus")
	proto.RegisterEnum("waste.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WasteClient is the client API for Waste service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WasteClient interface {
	Status(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Waste_StatusClient, error)
	RunChange(ctx context.Context, in *Change, opts ...grpc.CallOption) (*ChangeStatus, error)
}

type wasteClient struct {
	cc *grpc.ClientConn
}

func NewWasteClient(cc *grpc.ClientConn) WasteClient {
	return &wasteClient{cc}
}

func (c *wasteClient) Status(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Waste_StatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Waste_serviceDesc.Streams[0], "/waste.Waste/Status", opts...)
	if err != nil {
		return nil, err
	}
	x := &wasteStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Waste_StatusClient interface {
	Recv() (*ChangeStatus, error)
	grpc.ClientStream
}

type wasteStatusClient struct {
	grpc.ClientStream
}

func (x *wasteStatusClient) Recv() (*ChangeStatus, error) {
	m := new(ChangeStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wasteClient) RunChange(ctx context.Context, in *Change, opts ...grpc.CallOption) (*ChangeStatus, error) {
	out := new(ChangeStatus)
	err := c.cc.Invoke(ctx, "/waste.Waste/RunChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WasteServer is the server API for Waste service.
type WasteServer interface {
	Status(*Filter, Waste_StatusServer) error
	RunChange(context.Context, *Change) (*ChangeStatus, error)
}

func RegisterWasteServer(s *grpc.Server, srv WasteServer) {
	s.RegisterService(&_Waste_serviceDesc, srv)
}

func _Waste_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WasteServer).Status(m, &wasteStatusServer{stream})
}

type Waste_StatusServer interface {
	Send(*ChangeStatus) error
	grpc.ServerStream
}

type wasteStatusServer struct {
	grpc.ServerStream
}

func (x *wasteStatusServer) Send(m *ChangeStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Waste_RunChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Change)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasteServer).RunChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/waste.Waste/RunChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasteServer).RunChange(ctx, req.(*Change))
	}
	return interceptor(ctx, in, info, handler)
}

var _Waste_serviceDesc = grpc.ServiceDesc{
	ServiceName: "waste.Waste",
	HandlerType: (*WasteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunChange",
			Handler:    _Waste_RunChange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Status",
			Handler:       _Waste_Status_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "waste.proto",
}

func init() { proto.RegisterFile("waste.proto", fileDescriptor_waste_f5462c0924fc6b78) }

var fileDescriptor_waste_f5462c0924fc6b78 = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x51, 0x8b, 0xda, 0x4c,
	0x14, 0xfd, 0x62, 0x4c, 0xd4, 0x1b, 0xbf, 0x45, 0xa6, 0x7d, 0x48, 0xf3, 0xd0, 0x8a, 0x65, 0x61,
	0x69, 0x21, 0x16, 0x4b, 0x0b, 0x7d, 0xe8, 0x83, 0xb8, 0xee, 0x56, 0x58, 0xac, 0x8c, 0xb5, 0x7d,
	0x94, 0x31, 0x99, 0x8d, 0x42, 0xcc, 0xc8, 0xcc, 0x84, 0xfd, 0x17, 0xfd, 0x55, 0xfd, 0x61, 0x65,
	0xee, 0x24, 0x82, 0x56, 0xda, 0xb7, 0x9c, 0x39, 0xe7, 0xdc, 0xb9, 0xe7, 0xce, 0x0d, 0x04, 0x4f,
	0x4c, 0x69, 0x1e, 0x1f, 0xa4, 0xd0, 0x82, 0x78, 0x08, 0xa2, 0x57, 0x99, 0x10, 0x59, 0xce, 0x87,
	0x78, 0xb8, 0x29, 0x1f, 0x87, 0x7a, 0xb7, 0xe7, 0x4a, 0xb3, 0xfd, 0xc1, 0xea, 0xa2, 0x97, 0xe7,
	0x82, 0xb4, 0x94, 0x4c, 0xef, 0x44, 0x61, 0xf9, 0x01, 0x05, 0xff, 0x6e, 0x97, 0x6b, 0x2e, 0x09,
	0x81, 0x66, 0x59, 0xee, 0xd2, 0xd0, 0xe9, 0xbb, 0x37, 0x1d, 0x8a, 0xdf, 0x24, 0x82, 0x36, 0x93,
	0x7a, 0xf7, 0xc8, 0x12, 0x1d, 0x36, 0xf0, 0xfc, 0x88, 0x49, 0x08, 0xad, 0x24, 0x2f, 0x95, 0xe6,
	0x32, 0x74, 0x91, 0xaa, 0xe1, 0xe0, 0x23, 0x34, 0xbf, 0x08, 0xa5, 0x8d, 0x7b, 0x2b, 0x94, 0x2e,
	0xd8, 0x9e, 0x87, 0x4e, 0xdf, 0x31, 0xee, 0x1a, 0x9b, 0xdb, 0x0e, 0x42, 0x9a, 0xaa, 0xce, 0x8d,
	0x47, 0xf1, 0x7b, 0xf0, 0x04, 0xfe, 0xbd, 0x31, 0x2a, 0xf2, 0x1a, 0xfc, 0x9c, 0xb3, 0x94, 0x4b,
	0xf4, 0x05, 0xa3, 0x20, 0xb6, 0xd9, 0x0d, 0x4b, 0x2b, 0xca, 0x88, 0x94, 0x28, 0x65, 0xc2, 0xb1,
	0xc8, 0xb9, 0xc8, 0x52, 0x58, 0x89, 0x65, 0x19, 0x36, 0x79, 0xa1, 0x12, 0x52, 0x83, 0x5f, 0x0e,
	0xf8, 0x93, 0x2d, 0x2b, 0x32, 0x7e, 0x92, 0xb8, 0xea, 0xf9, 0x52, 0xe2, 0x06, 0x52, 0x35, 0x24,
	0x57, 0xd0, 0x48, 0x37, 0x78, 0x43, 0x87, 0x36, 0xd2, 0x0d, 0x79, 0x0e, 0x9e, 0x66, 0x9b, 0x9c,
	0x87, 0x4d, 0x3c, 0xb2, 0x80, 0xf4, 0xc0, 0x4d, 0xd3, 0x3c, 0xf4, 0xf0, 0xcc, 0x7c, 0x92, 0x6b,
	0x68, 0xd9, 0x30, 0x2a, 0xf4, 0xfb, 0xee, 0x79, 0x7b, 0x35, 0x47, 0xae, 0xc1, 0xcf, 0xa4, 0x28,
	0x0f, 0x2a, 0x6c, 0xa1, 0xea, 0xff, 0x4a, 0x65, 0xa7, 0x45, 0x2b, 0x72, 0xf0, 0xd3, 0x85, 0xae,
	0x8d, 0xb1, 0xd4, 0x4c, 0x97, 0x8a, 0x0c, 0xa1, 0x9b, 0x20, 0x5e, 0x2b, 0xcd, 0xb4, 0x7d, 0x84,
	0xab, 0x51, 0xb7, 0x72, 0x1b, 0x11, 0xa7, 0x41, 0x72, 0x74, 0x70, 0x93, 0x70, 0xcf, 0x95, 0x62,
	0x19, 0xaf, 0x13, 0x56, 0xf0, 0xb8, 0x1d, 0x36, 0xa3, 0xdd, 0x8e, 0xcf, 0xd0, 0x55, 0xc9, 0x96,
	0xa7, 0x65, 0xce, 0xd3, 0x35, 0xd3, 0x18, 0x36, 0x18, 0x45, 0xb1, 0x5d, 0xb9, 0xb8, 0x5e, 0xb9,
	0xf8, 0x5b, 0xbd, 0x93, 0x34, 0x38, 0xea, 0xc7, 0x9a, 0x7c, 0x02, 0x50, 0x9a, 0x49, 0xbd, 0x36,
	0x3b, 0x8b, 0x53, 0xf9, 0xbb, 0xb9, 0x83, 0x6a, 0x83, 0xc9, 0x07, 0x68, 0xf3, 0x22, 0xb5, 0x46,
	0xff, 0x9f, 0xc6, 0x16, 0x2f, 0x52, 0xb4, 0x45, 0xd0, 0x3e, 0x48, 0x91, 0x49, 0xae, 0xcc, 0x24,
	0xcd, 0xe2, 0x1d, 0x31, 0x79, 0x0b, 0x2e, 0xd7, 0x2c, 0x6c, 0x63, 0xb5, 0x17, 0x7f, 0x54, 0xbb,
	0xad, 0x7e, 0x1b, 0x6a, 0x54, 0xe6, 0x41, 0xec, 0xd8, 0xc2, 0x0e, 0xea, 0xeb, 0x07, 0xb1, 0xd3,
	0xa7, 0x15, 0xf9, 0x66, 0x06, 0x9e, 0x9d, 0x6b, 0x00, 0x2d, 0xba, 0x9a, 0xcf, 0x67, 0xf3, 0xfb,
	0xde, 0x7f, 0x06, 0x2c, 0xa6, 0xf3, 0x5b, 0x03, 0x1c, 0x03, 0x96, 0xab, 0xc9, 0x64, 0xba, 0x5c,
	0xf6, 0x1a, 0x06, 0xdc, 0x8d, 0x67, 0x0f, 0x2b, 0x3a, 0xed, 0xb9, 0xa4, 0x0b, 0xed, 0xf1, 0x62,
	0x41, 0xbf, 0x7e, 0x1f, 0x3f, 0xf4, 0x9a, 0xa3, 0x2d, 0x78, 0x3f, 0xcc, 0x15, 0x24, 0x06, 0xbf,
	0x7a, 0xdd, 0xfa, 0x52, 0xfb, 0xff, 0x46, 0xcf, 0x4e, 0x7a, 0xb0, 0x9a, 0x77, 0x0e, 0x19, 0x42,
	0x87, 0x96, 0x45, 0xb5, 0xdd, 0xa7, 0x7d, 0x5e, 0xb4, 0x6c, 0x7c, 0xcc, 0xfc, 0xfe, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x66, 0xcf, 0x8c, 0x1c, 0x6f, 0x04, 0x00, 0x00,
}
